export default {
  login: "shivaluma",
  id: 33391636,
  node_id: "MDQ6VXNlcjMzMzkxNjM2",
  avatar_url: "https://avatars3.githubusercontent.com/u/33391636?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/shivaluma",
  html_url: "https://github.com/shivaluma",
  followers_url: "https://api.github.com/users/shivaluma/followers",
  following_url:
    "https://api.github.com/users/shivaluma/following{/other_user}",
  gists_url: "https://api.github.com/users/shivaluma/gists{/gist_id}",
  starred_url: "https://api.github.com/users/shivaluma/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/shivaluma/subscriptions",
  organizations_url: "https://api.github.com/users/shivaluma/orgs",
  repos_url: "https://api.github.com/users/shivaluma/repos",
  events_url: "https://api.github.com/users/shivaluma/events{/privacy}",
  received_events_url: "https://api.github.com/users/shivaluma/received_events",
  type: "User",
  site_admin: false,
  score: 1.0,
};
